name: Smart Daily Code Touch

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 12:00 AM UTC
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update DoublyCLL.cpp with timestamp comment
        run: |
          echo "// Auto-update: $(date)" | cat - DoublyCLL.cpp > temp && mv temp DoublyCLL.cpp

      - name: Commit and push changes
        run: |
          git config --global user.name "vaibhavpatilX"
          git config --global user.email "patil.vaibhavx@gmail.com"
          git add DoublyCLL.cpp
          git commit -m "🤖 Daily update: Touched up DoublyCLL.cpp for practice"
          git push
