name: Smart Daily Code Touch

on:
  schedule:
    - cron: '0 0 * * *'  # Every day at 12:00 AM UTC
  workflow_dispatch:

jobs:
  smart-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace existing comment with a new one
        run: |
          COMMENT=$(shuf -n1 -e \
            "// Minor adjustment to node traversal" \
            "// Improved readability of pointer update" \
            "// Clarified linking between nodes" \
            "// Commented edge case handling" \
            "// Code refinement for loop structure" \
            "// Tweaked insertion point calculation" \
            "// Verified doubly link consistency" \
            "// Added explanation for InsertLast logic" \
            "// Refactored minor logic step" \
            "// Updated comment for InsertAtPos")

          # Remove previous auto-comment line(s)
          tail -n +2 DSA_Practice.cpp | sed '/^\/\/ [A-Z]/d' > temp.cpp

          # Add the new smart comment to the top
          echo "$COMMENT" > header.cpp
          cat header.cpp temp.cpp > DSA_Practice.cpp
          rm temp.cpp header.cpp

      - name: Commit and push
        run: |
          git config --global user.name "vaibhavpatilX"
          git config --global user.email "patil.vaibhavx@gmail.com"
          git add DSA_Practice.cpp
          git commit -m "🧠 Code clarity improvement on $(date +'%d-%m-%Y')"
          git push
